name: Pages-GitHub
on:
  push:
    branches:
    - main #触发的分支 

jobs:
  main-to-gh-pages:
    runs-on: ubuntu-latest
        
    steps:                          
    - name: checkout main
      uses: actions/checkout@v3
      with:
        ref: main

    - name: Get baseURL
      run: |
        baseURL=$(cat book.json | awk '/"Home": /' | awk '{print $2}' | sed "s|[\'\"]||g" | awk -F '//' '{print $2}' | sed "s|/||")
        if [[ $baseURL ]]; then
          echo "CNAME=$baseURL" >>$GITHUB_ENV
        else
          echo "Check baseURL setting in root book.json please."
          cat book.json
        fi
            
    - name: Install nodejs
      uses: actions/setup-node@v3
      with:
        node-version: 10
      
    - name: Install gitbook
      run: |
        npm install -g gitbook-cli          
        gitbook install
        npm install -g gitbook-summary
                
    - name: Build _book
      run: |
        book sm
        gitbook build
        cp SUMMARY.md _book
        mv -f README.md _book

    - name: Set CNAME
      if: ${{ ! contains(env.CNAME, 'github.io') }}
      run: echo ${{ env.CNAME }} >"_book/CNAME"

    - name: Deploy _book to branch pages-gitbook
      uses: peaceiris/actions-gh-pages@v3
      with:
        # github_token: ${{ secrets.GAYHUB_TOKEN }} # 该项适用于发布到源码相同repo的情况，不能用于发布到其他repo
        personal_token: ${{ secrets.ACTION_ACCESS_TOKEN }}	# 发布到其他repo需要提供上面生成的personal access token
        publish_dir: ./_book	# 注意这里指的是要发布哪个文件夹的内容，而不是指发布到目的仓库的什么位置
        external_repository: ${{ github.actor }}/${{ github.actor }}.github.io	# 发布到哪个repo
        publish_branch: pages-gitbook	# 发布到哪个branch
        user_name: 'github-actions[bot]'
        user_email: 'github-actions[bot]@users.noreply.github.com'
        force_orphan: true # make your publish branch with only the latest commit                
